const { initializeApp } = require('firebase/app');
const { getFirestore, collection, addDoc, Timestamp } = require('firebase/firestore');

const firebaseConfig = {
    apiKey: 'AIzaSyDIzCvfvDNrl7W6n_5Dvt2EKHsvhSuCaoA',
    authDomain: 'nextmeetbackend.firebaseapp.com',
    projectId: 'nextmeetbackend',
    storageBucket: 'nextmeetbackend.firebasestorage.app',
    messagingSenderId: '315326520856',
    appId: '1:315326520856:web:64c350cc5c917e11a06d6d',
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const chat = [
    { name: 'Sumit', msg: 'hi' },
    { name: 'Sumit', msg: 'Any one there' },
    { name: 'David', msg: 'Yeah! I found this site fascinating' },
    { name: 'David', msg: 'whr r u from' },
    { name: 'Sumit', msg: 'los Angles,' },
    { name: 'Sumit', msg: 'u' },
    { name: 'David', msg: 'mumbai' },
    { name: 'Sumit', msg: 'oh india' },
    { name: 'David', msg: 'i am from india, my fam migrated here' },
    { name: 'Sumit', msg: 'whr in india' },
    { name: 'David', msg: 'jodhpur' },
    { name: 'Sumit', msg: 'jodhpur is 6 hrs away frm here' },
    { name: 'David', msg: 'yeah' },
    { name: 'Sumit', msg: 'have u been back recently' },
    { name: 'David', msg: 'last year, went for diwali' },
    { name: 'Sumit', msg: 'nice man' },
    { name: 'Sumit', msg: 'jodhpur is beautiful' },
    { name: 'David', msg: 'yeah the blue city vibes r diff' },
    { name: 'Sumit', msg: 'u mean mehrangarh area' },
    { name: 'David', msg: 'yes exactly that side' },
    { name: 'Sumit', msg: 'i visited once in 2019' },
    { name: 'David', msg: 'amazing rite' },
    { name: 'Sumit', msg: 'totally, the food too omg' },
    { name: 'David', msg: 'dal baati churma' },
    { name: 'Sumit', msg: 'lol yes so heavy tho' },
    { name: 'David', msg: 'haha true' },
    { name: 'Sumit', msg: 'u staying in mumbai now or' },
    { name: 'David', msg: 'yeah mumbai only, u r in LA' },
    { name: 'Sumit', msg: 'yeah born here' },
    { name: 'David', msg: 'cool, how is it there' },
    { name: 'Sumit', msg: 'crazy busy lol' },
    { name: 'Sumit', msg: 'traffic is insane' },
    { name: 'David', msg: 'same as mumbai lmao' },
    { name: 'Sumit', msg: 'haha no way mumbai wins that' },
    { name: 'David', msg: 'whr in mumbai u stay' },
    { name: 'Sumit', msg: 'andheri west' },
    { name: 'David', msg: 'oh nice area' },
    { name: 'Sumit', msg: 'yeah its ok, crowded tho' },
    { name: 'David', msg: 'lol every part of mumbai is crowded' },
    { name: 'Sumit', msg: 'true true' },
    { name: 'David', msg: 'u work there or study' },
    { name: 'Sumit', msg: 'work, IT field' },
    { name: 'David', msg: 'same here bro' },
    { name: 'Sumit', msg: 'really, which company' },
    { name: 'David', msg: 'startup, u' },
    { name: 'Sumit', msg: 'MNC, been here 2 yrs' },
    { name: 'David', msg: 'nice bro' },
    { name: 'David', msg: 'LA has lottt of tech jobs' },
    { name: 'Sumit', msg: 'yeah silicon valley is near rite' },
    { name: 'David', msg: 'not that near but yeah same vibe' },
    { name: 'Sumit', msg: 'got it' },
    { name: 'David', msg: 'u ever thought of coming to US' },
    { name: 'Sumit', msg: 'tbh yes but visa is pain' },
    { name: 'David', msg: 'haha yeah its tough' },
    { name: 'Sumit', msg: 'how did ur family go there' },
    { name: 'David', msg: 'dad went on work visa like 20 yrs back' },
    { name: 'Sumit', msg: 'ohh long time' },
    { name: 'David', msg: 'yeah settled now' },
    { name: 'Sumit', msg: 'must be nice' },
    { name: 'David', msg: 'it is but miss india sometimes' },
    { name: 'Sumit', msg: 'the food mostly rite lol' },
    { name: 'David', msg: 'HAHA yes bro' },
    { name: 'David', msg: 'and festivals' },
    { name: 'Sumit', msg: 'same, diwali hits diff here' },
    { name: 'David', msg: 'exactly not the same outside india' },
    { name: 'Sumit', msg: 'u celebrate diwali in mumbai with fam' },
    { name: 'David', msg: 'yeah every year, big thing in our house' },
    { name: 'Sumit', msg: 'nice man' },
    { name: 'Sumit', msg: 'we do small celebration here' },
    { name: 'David', msg: 'still good na' },
    { name: 'Sumit', msg: 'yeah but neighbours complain abt crackers lol' },
    { name: 'David', msg: 'haha same issue here too now' },
    { name: 'David', msg: 'govt banned most crackers' },
    { name: 'Sumit', msg: 'really' },
    { name: 'David', msg: 'yeah pollution thing' },
    { name: 'Sumit', msg: 'makes sense i guess' },
    { name: 'David', msg: 'yeah but feels diff without them' },
    { name: 'Sumit', msg: 'totally' },
    { name: 'Sumit', msg: 'holi how is it there' },
    { name: 'David', msg: 'maddd fun bro' },
    { name: 'David', msg: 'whole colony plays' },
    { name: 'Sumit', msg: 'jealous honestly' },
    { name: 'David', msg: 'u dont get holi there' },
    { name: 'Sumit', msg: 'some events happen but its not the same' },
    { name: 'David', msg: 'yeah real holi is street level' },
    { name: 'Sumit', msg: 'exactly' },
    { name: 'Sumit', msg: 'do u travel much within india' },
    { name: 'David', msg: 'not much, work keeps busy' },
    { name: 'David', msg: 'u went anywhere else in rajasthan' },
    { name: 'Sumit', msg: 'jaipur also' },
    { name: 'David', msg: 'pink city' },
    { name: 'Sumit', msg: 'haha yeah all colour cities in rajasthan' },
    { name: 'David', msg: 'udaipur also is beautiful' },
    { name: 'Sumit', msg: 'been there' },
    { name: 'David', msg: 'once for a cousin wedding' },
    { name: 'Sumit', msg: 'lucky bro weddings there must be royal' },
    { name: 'David', msg: 'was insane honestly' },
    { name: 'David', msg: '3 days function' },
    { name: 'Sumit', msg: '3 days' },
    { name: 'David', msg: 'normal for us lol' },
    { name: 'Sumit', msg: 'american weddings r like 2 hrs and done' },
    { name: 'David', msg: 'lmaooo' },
    { name: 'David', msg: 'our caterer alone feeds 1000 people' },
    { name: 'Sumit', msg: 'bro thats a whole festival' },
    { name: 'David', msg: 'IT IS lol' },
    { name: 'Sumit', msg: 'i wanna attend an indian wedding properly one day' },
    { name: 'David', msg: 'come for next one ill invite u' },
    { name: 'Sumit', msg: 'haha deal bro' },
    { name: 'Sumit', msg: 'so how did u find this site' },
    { name: 'David', msg: 'was just browsing randomly' },
    { name: 'Sumit', msg: 'same honestly' },
    { name: 'David', msg: 'seems like mostly indians and NRIs here' },
    { name: 'Sumit', msg: 'lol maybe' },
    { name: 'Sumit', msg: 'or people curious abt india' },
    { name: 'David', msg: 'could be' },
    { name: 'Sumit', msg: 'its a cool concept tho' },
    { name: 'David', msg: 'yeah random chat is fun sometimes' },
    { name: 'Sumit', msg: 'better than scrolling insta for 2 hrs' },
    { name: 'David', msg: 'haha facts' },
    { name: 'Sumit', msg: 'u on insta' },
    { name: 'David', msg: 'yeah but barely post' },
    { name: 'Sumit', msg: 'same bro just a lurker' },
    { name: 'David', msg: 'same same' },
    { name: 'Sumit', msg: 'what kind of content u like on insta' },
    { name: 'David', msg: 'mostly tech and memes lol' },
    { name: 'Sumit', msg: 'haha same bro' },
    { name: 'Sumit', msg: 'and food reels' },
    { name: 'David', msg: 'oh yes food reels are dangerous' },
    { name: 'Sumit', msg: 'u end up hungry at 1am' },
    { name: 'David', msg: 'every single time' },
    { name: 'Sumit', msg: 'lol bro' },
    { name: 'Sumit', msg: 'ok so wht do u do on weekends' },
    { name: 'David', msg: 'chill mostly, sometimes outing with friends' },
    { name: 'Sumit', msg: 'where u guys go' },
    { name: 'David', msg: 'marine drive, bandra side' },
    { name: 'Sumit', msg: 'bandra is so iconic' },
    { name: 'David', msg: 'yeah livelyyy place' },
    { name: 'Sumit', msg: 'heard carter road is nice' },
    { name: 'David', msg: 'yes evenings there r great' },
    { name: 'Sumit', msg: 'jealous again lol' },
    { name: 'David', msg: 'LA has beaches no' },
    { name: 'Sumit', msg: 'yeah but diff vibe' },
    { name: 'David', msg: 'true mumbai sea has its own feel' },
    { name: 'Sumit', msg: 'especially monsoon i heard' },
    { name: 'David', msg: 'bro monsoon in mumbai is another level' },
    { name: 'Sumit', msg: 'good or bad lol' },
    { name: 'David', msg: 'both honestly' },
    { name: 'David', msg: 'romantic but also chaos' },
    { name: 'Sumit', msg: 'waterlogging and all' },
    { name: 'David', msg: 'yes trains stop, roads flood' },
    { name: 'Sumit', msg: 'still people love it' },
    { name: 'David', msg: 'its mumbai bro city never stops' },
    { name: 'Sumit', msg: 'respect honestly' },
    { name: 'David', msg: 'haha thnx' },
    { name: 'Sumit', msg: 'ok bro was nice talking' },
    { name: 'David', msg: 'same man, good chat' },
    { name: 'Sumit', msg: 'take care' },
    { name: 'David', msg: 'u too bro, tc' },
];

let idx = 0;

async function post() {
    if (idx >= chat.length) {
        console.log('\n🔄 Restarting conversation...\n');
        idx = 0;
    }

    const { name, msg } = chat[idx];
    const uid = name === 'Sumit' ? 'user-sumit' : 'chat-David';
    idx++;

    try {
        await addDoc(collection(db, 'globalChat'), {
            sender: { name, uid },
            message: msg,
            timestamp: new Date().toISOString(),
            createdAt: Timestamp.fromDate(new Date()),
        });
        console.log(`[${idx}/${chat.length}] ${name}: ${msg}`);
    } catch (e) {
        console.error('Error:', e.message);
    }

    const delay = 4000 + Math.random() * 2000;
    setTimeout(post, delay);
}

console.log(`🤖 Posting ${chat.length} messages on loop (4-6s interval)`);
console.log('   Ctrl+C to stop\n');
post();
