const { initializeApp } = require('firebase/app');
const { getFirestore, collection, addDoc } = require('firebase/firestore');

const firebaseConfig = {
    apiKey: 'AIzaSyDIzCvfvDNrl7W6n_5Dvt2EKHsvhSuCaoA',
    authDomain: 'nextmeetbackend.firebaseapp.com',
    projectId: 'nextmeetbackend',
    storageBucket: 'nextmeetbackend.firebasestorage.app',
    messagingSenderId: '315326520856',
    appId: '1:315326520856:web:64c350cc5c917e11a06d6d',
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const script1 = [
    { name: 'Sumit', msg: 'hi' },
    { name: 'Sumit', msg: 'Any one there' },
    { name: 'David', msg: 'Yeah! I found this site fascinating' },
    { name: 'David', msg: 'whr r u from' },
    { name: 'Sumit', msg: 'los Angles,' },
    { name: 'Sumit', msg: 'u' },
    { name: 'David', msg: 'mumbai' },
    { name: 'Sumit', msg: 'oh india' },
    { name: 'David', msg: 'i am from india, my fam migrated here' },
    { name: 'Sumit', msg: 'whr in india' },
    { name: 'David', msg: 'jodhpur' },
    { name: 'Sumit', msg: 'jodhpur is 6 hrs away frm here' },
    { name: 'David', msg: 'yeah' },
    { name: 'Sumit', msg: 'have u been back recently' },
    { name: 'David', msg: 'last year, went for diwali' },
    { name: 'Sumit', msg: 'nice man' },
    { name: 'Sumit', msg: 'jodhpur is beautiful' },
    { name: 'David', msg: 'yeah the blue city vibes r diff' },
    { name: 'Sumit', msg: 'u mean mehrangarh area' },
    { name: 'David', msg: 'yes exactly that side' },
    { name: 'Sumit', msg: 'i visited once in 2019' },
    { name: 'David', msg: 'amazing rite' },
    { name: 'Sumit', msg: 'totally, the food too omg' },
    { name: 'David', msg: 'dal baati churma' },
    { name: 'Sumit', msg: 'lol yes so heavy tho' },
    { name: 'David', msg: 'haha true' },
    { name: 'Sumit', msg: 'u staying in mumbai now or' },
    { name: 'David', msg: 'yeah mumbai only, u r in LA' },
    { name: 'Sumit', msg: 'yeah born here' },
    { name: 'David', msg: 'cool, how is it there' },
    { name: 'Sumit', msg: 'crazy busy lol' },
    { name: 'Sumit', msg: 'traffic is insane' },
    { name: 'David', msg: 'same as mumbai lmao' },
    { name: 'Sumit', msg: 'haha no way mumbai wins that' },
    { name: 'David', msg: 'whr in mumbai u stay' },
    { name: 'Sumit', msg: 'andheri west' },
    { name: 'David', msg: 'oh nice area' },
    { name: 'Sumit', msg: 'yeah its ok, crowded tho' },
    { name: 'David', msg: 'lol every part of mumbai is crowded' },
    { name: 'Sumit', msg: 'true true' },
    { name: 'David', msg: 'u work there or study' },
    { name: 'Sumit', msg: 'work, IT field' },
    { name: 'David', msg: 'same here bro' },
    { name: 'Sumit', msg: 'really, which company' },
    { name: 'David', msg: 'startup, u' },
    { name: 'Sumit', msg: 'MNC, been here 2 yrs' },
    { name: 'David', msg: 'nice bro' },
    { name: 'David', msg: 'LA has lottt of tech jobs' },
    { name: 'Sumit', msg: 'yeah silicon valley is near rite' },
    { name: 'David', msg: 'not that near but yeah same vibe' },
    { name: 'Sumit', msg: 'got it' },
    { name: 'David', msg: 'u ever thought of coming to US' },
    { name: 'Sumit', msg: 'tbh yes but visa is pain' },
    { name: 'David', msg: 'haha yeah its tough' },
    { name: 'Sumit', msg: 'how did ur family go there' },
    { name: 'David', msg: 'dad went on work visa like 20 yrs back' },
    { name: 'Sumit', msg: 'ohh long time' },
    { name: 'David', msg: 'yeah settled now' },
    { name: 'Sumit', msg: 'must be nice' },
    { name: 'David', msg: 'it is but miss india sometimes' },
    { name: 'Sumit', msg: 'the food mostly rite lol' },
    { name: 'David', msg: 'HAHA yes bro' },
    { name: 'David', msg: 'and festivals' },
    { name: 'Sumit', msg: 'same, diwali hits diff here' },
    { name: 'David', msg: 'exactly not the same outside india' },
    { name: 'Sumit', msg: 'u celebrate diwali in mumbai with fam' },
    { name: 'David', msg: 'yeah every year, big thing in our house' },
    { name: 'Sumit', msg: 'nice man' },
    { name: 'Sumit', msg: 'we do small celebration here' },
    { name: 'David', msg: 'still good na' },
    { name: 'Sumit', msg: 'yeah but neighbours complain abt crackers lol' },
    { name: 'David', msg: 'haha same issue here too now' },
    { name: 'David', msg: 'govt banned most crackers' },
    { name: 'Sumit', msg: 'really' },
    { name: 'David', msg: 'yeah pollution thing' },
    { name: 'Sumit', msg: 'makes sense i guess' },
    { name: 'David', msg: 'yeah but feels diff without them' },
    { name: 'Sumit', msg: 'totally' },
    { name: 'Sumit', msg: 'holi how is it there' },
    { name: 'David', msg: 'maddd fun bro' },
    { name: 'David', msg: 'whole colony plays' },
    { name: 'Sumit', msg: 'jealous honestly' },
    { name: 'David', msg: 'u dont get holi there' },
    { name: 'Sumit', msg: 'some events happen but its not the same' },
    { name: 'David', msg: 'yeah real holi is street level' },
    { name: 'Sumit', msg: 'exactly' },
    { name: 'Sumit', msg: 'do u travel much within india' },
    { name: 'David', msg: 'not much, work keeps busy' },
    { name: 'David', msg: 'u went anywhere else in rajasthan' },
    { name: 'Sumit', msg: 'jaipur also' },
    { name: 'David', msg: 'pink city' },
    { name: 'Sumit', msg: 'haha yeah all colour cities in rajasthan' },
    { name: 'David', msg: 'udaipur also is beautiful' },
    { name: 'Sumit', msg: 'been there' },
    { name: 'David', msg: 'once for a cousin wedding' },
    { name: 'Sumit', msg: 'lucky bro weddings there must be royal' },
    { name: 'David', msg: 'was insane honestly' },
    { name: 'David', msg: '3 days function' },
    { name: 'Sumit', msg: '3 days' },
    { name: 'David', msg: 'normal for us lol' },
    { name: 'Sumit', msg: 'american weddings r like 2 hrs and done' },
    { name: 'David', msg: 'lmaooo' },
    { name: 'David', msg: 'our caterer alone feeds 1000 people' },
    { name: 'Sumit', msg: 'bro thats a whole festival' },
    { name: 'David', msg: 'IT IS lol' },
    { name: 'Sumit', msg: 'i wanna attend an indian wedding properly one day' },
    { name: 'David', msg: 'come for next one ill invite u' },
    { name: 'Sumit', msg: 'haha deal bro' },
    { name: 'Sumit', msg: 'so how did u find this site' },
    { name: 'David', msg: 'was just browsing randomly' },
    { name: 'Sumit', msg: 'same honestly' },
    { name: 'David', msg: 'seems like mostly indians and NRIs here' },
    { name: 'Sumit', msg: 'lol maybe' },
    { name: 'Sumit', msg: 'or people curious abt india' },
    { name: 'David', msg: 'could be' },
    { name: 'Sumit', msg: 'its a cool concept tho' },
    { name: 'David', msg: 'yeah random chat is fun sometimes' },
    { name: 'Sumit', msg: 'better than scrolling insta for 2 hrs' },
    { name: 'David', msg: 'haha facts' },
    { name: 'Sumit', msg: 'u on insta' },
    { name: 'David', msg: 'yeah but barely post' },
    { name: 'Sumit', msg: 'same bro just a lurker' },
    { name: 'David', msg: 'same same' },
    { name: 'Sumit', msg: 'what kind of content u like on insta' },
    { name: 'David', msg: 'mostly tech and memes lol' },
    { name: 'Sumit', msg: 'haha same bro' },
    { name: 'Sumit', msg: 'and food reels' },
    { name: 'David', msg: 'oh yes food reels are dangerous' },
    { name: 'Sumit', msg: 'u end up hungry at 1am' },
    { name: 'David', msg: 'every single time' },
    { name: 'Sumit', msg: 'lol bro' },
    { name: 'Sumit', msg: 'ok so wht do u do on weekends' },
    { name: 'David', msg: 'chill mostly, sometimes outing with friends' },
    { name: 'Sumit', msg: 'where u guys go' },
    { name: 'David', msg: 'marine drive, bandra side' },
    { name: 'Sumit', msg: 'bandra is so iconic' },
    { name: 'David', msg: 'yeah livelyyy place' },
    { name: 'Sumit', msg: 'heard carter road is nice' },
    { name: 'David', msg: 'yes evenings there r great' },
    { name: 'Sumit', msg: 'jealous again lol' },
    { name: 'David', msg: 'LA has beaches no' },
    { name: 'Sumit', msg: 'yeah but diff vibe' },
    { name: 'David', msg: 'true mumbai sea has its own feel' },
    { name: 'Sumit', msg: 'especially monsoon i heard' },
    { name: 'David', msg: 'bro monsoon in mumbai is another level' },
    { name: 'Sumit', msg: 'good or bad lol' },
    { name: 'David', msg: 'both honestly' },
    { name: 'David', msg: 'romantic but also chaos' },
    { name: 'Sumit', msg: 'waterlogging and all' },
    { name: 'David', msg: 'yes trains stop, roads flood' },
    { name: 'Sumit', msg: 'still people love it' },
    { name: 'David', msg: 'its mumbai bro city never stops' },
    { name: 'Sumit', msg: 'respect honestly' },
    { name: 'David', msg: 'haha thnx' },
    { name: 'Sumit', msg: 'ok bro was nice talking' },
    { name: 'David', msg: 'same man, good chat' },
    { name: 'Sumit', msg: 'take care' },
    { name: 'David', msg: 'u too bro, tc' },
];

const script2 = [
    { name: 'Nidhi', msg: 'anyone here' },
    { name: 'Aksh Das', msg: 'hi' },
    { name: 'Nidhi', msg: 'hey' },
    { name: 'Aksh Das', msg: 'how r u' },
    { name: 'Nidhi', msg: 'good u' },
    { name: 'Aksh Das', msg: 'good good' },
    { name: 'Aksh Das', msg: 'whr r u from' },
    { name: 'Nidhi', msg: 'bangalore, u' },
    { name: 'Aksh Das', msg: 'kolkata' },
    { name: 'Nidhi', msg: 'oh nice' },
    { name: 'Aksh Das', msg: 'u born there or shifted' },
    { name: 'Nidhi', msg: 'born here only' },
    { name: 'Aksh Das', msg: 'ok ok' },
    { name: 'Nidhi', msg: 'u born in kolkata' },
    { name: 'Aksh Das', msg: 'yes lifelong kolkatan lol' },
    { name: 'Nidhi', msg: 'haha nice' },
    { name: 'Nidhi', msg: 'kolkata seems like chill city' },
    { name: 'Aksh Das', msg: 'very chill compared to bangalore i think' },
    { name: 'Nidhi', msg: 'bangalore is not chill at all lol' },
    { name: 'Aksh Das', msg: 'traffic right' },
    { name: 'Nidhi', msg: 'bro the traffic is a nightmare' },
    { name: 'Aksh Das', msg: 'heard it so many times' },
    { name: 'Nidhi', msg: 'its getting worse every year' },
    { name: 'Aksh Das', msg: 'kolkata also has but not that bad' },
    { name: 'Nidhi', msg: 'lucky u' },
    { name: 'Aksh Das', msg: 'haha yeah' },
    { name: 'Aksh Das', msg: 'so what do u do' },
    { name: 'Nidhi', msg: 'software engineer, u' },
    { name: 'Aksh Das', msg: 'arts student, final year' },
    { name: 'Nidhi', msg: 'oh cool which college' },
    { name: 'Aksh Das', msg: 'presidency university' },
    { name: 'Nidhi', msg: 'oh thats a big name' },
    { name: 'Aksh Das', msg: 'yeah old college lots of history' },
    { name: 'Nidhi', msg: 'must be nice studying there' },
    { name: 'Aksh Das', msg: 'it is, the campus is old but beautiful' },
    { name: 'Nidhi', msg: 'i always wanted to visit kolkata' },
    { name: 'Aksh Das', msg: 'u never came' },
    { name: 'Nidhi', msg: 'never got chance' },
    { name: 'Aksh Das', msg: 'u should come in winter' },
    { name: 'Nidhi', msg: 'december' },
    { name: 'Aksh Das', msg: 'yes december is best time' },
    { name: 'Nidhi', msg: 'durga puja time i missed' },
    { name: 'Aksh Das', msg: 'oh thats october, u should plan that' },
    { name: 'Nidhi', msg: 'is it as big as they show' },
    { name: 'Aksh Das', msg: 'bro it is 10x bigger than they show' },
    { name: 'Nidhi', msg: 'seriously' },
    { name: 'Aksh Das', msg: 'whole city transforms' },
    { name: 'Aksh Das', msg: 'every para has its own pandal' },
    { name: 'Nidhi', msg: 'para means area right' },
    { name: 'Aksh Das', msg: 'yes neighbourhood basically' },
    { name: 'Nidhi', msg: 'and they compete with each other' },
    { name: 'Aksh Das', msg: 'yes big competition, themes and lighting everything' },
    { name: 'Nidhi', msg: 'that sounds insane' },
    { name: 'Aksh Das', msg: 'it is honestly nothing like it' },
    { name: 'Nidhi', msg: 'we have dasara here in bangalore' },
    { name: 'Aksh Das', msg: 'oh yes mysore dasara is famous' },
    { name: 'Nidhi', msg: 'yes we go mysore for that sometimes' },
    { name: 'Aksh Das', msg: 'how far is mysore from bangalore' },
    { name: 'Nidhi', msg: 'like 3 hrs' },
    { name: 'Aksh Das', msg: 'not bad' },
    { name: 'Nidhi', msg: 'yeah doable for a weekend' },
    { name: 'Aksh Das', msg: 'bangalore has good weather right' },
    { name: 'Nidhi', msg: 'yes that is the only saving grace lol' },
    { name: 'Aksh Das', msg: 'haha compared to kolkata our humidity is torture' },
    { name: 'Nidhi', msg: 'really that bad' },
    { name: 'Aksh Das', msg: 'summer here is brutal' },
    { name: 'Nidhi', msg: 'bangalore is always 20 to 28 mostly' },
    { name: 'Aksh Das', msg: 'i want to move there honestly' },
    { name: 'Nidhi', msg: 'for weather or work' },
    { name: 'Aksh Das', msg: 'both lol' },
    { name: 'Nidhi', msg: 'lots of jobs here if u r in tech' },
    { name: 'Aksh Das', msg: 'i am arts so not sure' },
    { name: 'Nidhi', msg: 'content, design, media all here too' },
    { name: 'Aksh Das', msg: 'true bangalore has that scene now' },
    { name: 'Nidhi', msg: 'yes its growing' },
    { name: 'Aksh Das', msg: 'kolkata is slow in that' },
    { name: 'Nidhi', msg: 'but kolkata has culture na' },
    { name: 'Aksh Das', msg: 'yes that we have in loads' },
    { name: 'Nidhi', msg: 'music, art, literature' },
    { name: 'Aksh Das', msg: 'yes very big here' },
    { name: 'Aksh Das', msg: 'rabindra sangeet, adda culture' },
    { name: 'Nidhi', msg: 'adda means just chatting right' },
    { name: 'Aksh Das', msg: 'yes sitting and talking for hours' },
    { name: 'Nidhi', msg: 'that sounds peaceful honestly' },
    { name: 'Aksh Das', msg: 'it is our favourite thing lol' },
    { name: 'Nidhi', msg: 'bangalore people r more pub culture' },
    { name: 'Aksh Das', msg: 'haha yeah i noticed that' },
    { name: 'Nidhi', msg: 'koramangala indiranagar full of pubs' },
    { name: 'Aksh Das', msg: 'u go often' },
    { name: 'Nidhi', msg: 'sometimes with office friends' },
    { name: 'Aksh Das', msg: 'kolkata also getting that scene slowly' },
    { name: 'Nidhi', msg: 'good food there i heard' },
    { name: 'Aksh Das', msg: 'bro kolkata food is underrated' },
    { name: 'Nidhi', msg: 'kathi rolls right' },
    { name: 'Aksh Das', msg: 'yes and mishti doi, kosha mangsho' },
    { name: 'Nidhi', msg: 'kosha mangsho is mutton right' },
    { name: 'Aksh Das', msg: 'yes slow cooked, best thing ever' },
    { name: 'Nidhi', msg: 'i am vegetarian so' },
    { name: 'Aksh Das', msg: 'oh then mishti doi and rasgulla for u' },
    { name: 'Nidhi', msg: 'haha i love sweets so works' },
    { name: 'Aksh Das', msg: 'kolkata sweets r legendary' },
    { name: 'Nidhi', msg: 'we have good filter coffee here' },
    { name: 'Aksh Das', msg: 'i need to try that' },
    { name: 'Nidhi', msg: 'if u come bangalore must try' },
    { name: 'Aksh Das', msg: 'deal' },
    { name: 'Nidhi', msg: 'so what do u do for fun in kolkata' },
    { name: 'Aksh Das', msg: 'adda, book fair, movie' },
    { name: 'Nidhi', msg: 'book fair sounds fun' },
    { name: 'Aksh Das', msg: 'kolkata book fair is massive' },
    { name: 'Nidhi', msg: 'how big' },
    { name: 'Aksh Das', msg: 'lakhs of people, month long event' },
    { name: 'Nidhi', msg: 'seriously' },
    { name: 'Aksh Das', msg: 'yes every january february' },
    { name: 'Nidhi', msg: 'i had no idea' },
    { name: 'Aksh Das', msg: 'most people dont' },
    { name: 'Nidhi', msg: 'bangalore has comic con and stuff' },
    { name: 'Aksh Das', msg: 'oh yes that is fun' },
    { name: 'Nidhi', msg: 'u been' },
    { name: 'Aksh Das', msg: 'no not yet' },
    { name: 'Nidhi', msg: 'u should come here for that sometime' },
    { name: 'Aksh Das', msg: 'maybe after college' },
    { name: 'Nidhi', msg: 'job plans after' },
    { name: 'Aksh Das', msg: 'not sure yet, maybe content writing or journalism' },
    { name: 'Nidhi', msg: 'both good fields' },
    { name: 'Aksh Das', msg: 'pays less than tech tho lol' },
    { name: 'Nidhi', msg: 'haha yeah but if u love it' },
    { name: 'Aksh Das', msg: 'true' },
    { name: 'Nidhi', msg: 'passion matters' },
    { name: 'Aksh Das', msg: 'easy to say hard to live lol' },
    { name: 'Nidhi', msg: 'haha fair point' },
    { name: 'Aksh Das', msg: 'r u happy in software' },
    { name: 'Nidhi', msg: 'mostly yes, good money but hectic' },
    { name: 'Aksh Das', msg: 'deadlines and all' },
    { name: 'Nidhi', msg: 'yes and on call sometimes' },
    { name: 'Aksh Das', msg: 'sounds stressful' },
    { name: 'Nidhi', msg: 'it is but u get used to it' },
    { name: 'Aksh Das', msg: 'how long u been working' },
    { name: 'Nidhi', msg: '3 years now' },
    { name: 'Aksh Das', msg: 'still young' },
    { name: 'Nidhi', msg: 'haha thanks' },
    { name: 'Aksh Das', msg: 'i am 21 u' },
    { name: 'Nidhi', msg: '25' },
    { name: 'Aksh Das', msg: 'ok ok senior lol' },
    { name: 'Nidhi', msg: 'stop it lol' },
    { name: 'Aksh Das', msg: 'haha just kidding' },
    { name: 'Nidhi', msg: 'its fine' },
    { name: 'Aksh Das', msg: 'this was nice chat' },
    { name: 'Nidhi', msg: 'yes really good actually' },
    { name: 'Aksh Das', msg: 'random chats r fun' },
    { name: 'Nidhi', msg: 'yeah u never know who u meet' },
    { name: 'Aksh Das', msg: 'true' },
    { name: 'Nidhi', msg: 'ok i should get back to work' },
    { name: 'Aksh Das', msg: 'office hours lol' },
    { name: 'Nidhi', msg: 'unfortunately yes' },
    { name: 'Aksh Das', msg: 'ok take care nidhi' },
];

async function seed() {
    console.log('Seeding scripts to Firestore...\n');

    await addDoc(collection(db, 'chatScripts'), {
        name: 'Sumit & David',
        messages: script1,
    });
    console.log(`✓ Script 1: Sumit & David (${script1.length} msgs)`);

    await addDoc(collection(db, 'chatScripts'), {
        name: 'Nidhi & Aksh Das',
        messages: script2,
    });
    console.log(`✓ Script 2: Nidhi & Aksh Das (${script2.length} msgs)`);

    console.log('\nDone! Scripts stored in chatScripts collection.');
    process.exit(0);
}

seed().catch((e) => { console.error('Error:', e); process.exit(1); });
